a = input('Digite algo: ')
print('O tipo primitivo desse valor é ', type(a))
print('Só tem espaços? ', a.isspace())
print('É um numérico?', a.isnumeric())
print('É alfabético? ', a.isalpha())
print('É alfanumérico? ', a.isupper())
print('Esta em maiúsculas? ', a.isupper() )
print('Está minúsculas? ', a.islower())
print('Está capitalizada? ', a.istitle())